apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dn0wscesz-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dn0wscesz-nodejs 
  name: dn0wscesz-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: dn0wscesz-nodejs 
